#Рандомизировать кошельки? true / false
IS_RANDOM = false

#Количество $, на которые хотите бриджить в Merkly за 1 транзакцию, к этому числу прибавляется комиссия Merkly
#Для Klay комиссия ±0.36 KLAY, для Polygon ±0.018 MATIC
#Для Klay не реккомендуется ставить больше 0.003
VALUE_FROM = 0.001
VALUE_TO = 0.003

#Количество транзакций на каждом кошельке
TRANSACTION_FROM = 1
TRANSACTION_TO = 2

#Задержка между транзакицями в секнудах
TRANSACTION_DELAY_FROM = 20
TRANSACTION_DELAY_TO = 40

#Задержка между аккаунтами в секундах
ACCOUNT_DELAY_FROM = 20
ACCOUNT_DELAY_TO = 30

[RPCs]
Klaytn = "https://1rpc.io/klay"
Polygon = 'https://rpc.ankr.com/polygon'
